ingress:
  enabled: false

backend:
  hostname: gargantua.hobbyfarm

# seed with some example data
seed:
  enabled: true

# https://github.com/rancher/terraform-controller
terraform:
  enabled: true
  executor_image: "oats87/terraform-controller-executor:hfv1"

  # one of: ranchervm, aws, vsphere (untested), do (untested)
  provider: aws

  ranchervm:
    image: rancher/vm-ubuntu:16.04.5-server-amd64
    endpoint: "http://backend.ranchervm-system:9500"

  aws:
    image: ami-04763b3055de4860b
    region: us-east-1

    access_key:
    secret_key:
    subnet:
    vpc_security_group_id:

# https://github.com/hobbyfarm/vm
ranchervm:
  enabled: false
  nic: "eth0"
  bridge: "docker0"
