apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      component: ui
  template:
    metadata:
      labels:
        component: ui
    spec:
      containers:
        - name: ui
          image: {{ $.Values.ui.image }}
          env:
            - name: HF_SERVER
              {{ if $.Values.ingress.enabled }}
              value: {{ $.Values.ingress.hostnames.backend | quote }}
              {{ else }}
              value: {{ print "gargantua." $.Release.Namespace | quote }}
              {{ end }}
