apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      component: ui
  template:
    metadata:
      labels:
        component: ui
    spec:
      containers:
        - name: ui
          image: {{ $.Values.ui.image }}
          env:
            - name: HF_SERVER
              {{ if $.Values.ingress.enabled }}
              value: {{ print "https://" $.Values.ingress.hostnames.backend | quote }}
              {{ else }}
              value: {{ print "http://gargantua." $.Release.Namespace | quote }}
              {{ end }}
      {{- if $.Values.ui.configMapName }}
          volumeMounts:
            - name: config
              mountPath: /usr/share/nginx/html/config.json
              subPath: config.json
      volumes:
        - name: config
          configMap: 
            name: {{ $.Values.ui.configMapName }}
      {{- end }}
