apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gargantua
rules:
- apiGroups: ["hobbyfarm.io", "terraformcontroller.cattle.io"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gargantua
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: default
roleRef:
  kind: ClusterRole
  name: gargantua
  apiGroup: rbac.authorization.k8s.io