apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      component: ui
  template:
    metadata:
      labels:
        component: ui
    spec:
      containers:
        - name: ui
          # image: hobbyfarm/ui:0.2.0
          image: brytonhall/ui:latest
          env:
            - name: HF_SERVER
              value: {{ .Values.backend.hostname }}

