{{ if and .Values.seed.enabled (eq .Values.terraform.provider "ranchervm") }}
apiVersion: vm.rancher.io/v1alpha1
kind: MachineImage
metadata:
  # name: vm-ubuntu-1604-final
  name: example-image
spec:
  docker_image: {{ .Values.terraform.ranchervm.image }}
  size_gib: 1
{{ end }}