{{ if .Values.seed.enabled }}
apiVersion: hobbyfarm.io/v1
kind: ScheduledEvent
metadata:
  name: example-event
spec:
  start_time: {{ now | date "Mon Jan 2 15:04:05 MST 2006" }}
  end_time: {{ now | date_modify "+2h" | date "Mon Jan 2 15:04:05 MST 2006" }}
  required_vms:
    example-environment:
      ubuntu1604-docker1: 2
  access_code: example
  scenarios:
    - example-scenario
status:
  active: true
{{ end }}