{{ if .Values.ranchervm.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ranchervm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: frontend
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: frontend
        image: rancher/vm-frontend:v0.2.0
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: ranchervm-system
spec:
  ports:
  - name: ui
    port: 80
    targetPort: 8000
  selector:
    app: frontend
  type: LoadBalancer
{{ end }}